### ISSUE TITLE
working sample

### ISSUE THREAD

**Issue by mninawa** [alexander-trishin/replace-token#16]
Hi Alex
im looking for a working sample of the replace token.. please help

**Comment by alexander-trishin** [comment]
Hi @mninawa,

Here is the simplest example of using this action:

<details>
  <summary>File: before</summary>

src/example.txt

```
Lorem ipsum dolor sit amet, consectetur ${{ REPLACE_ME }} elit...
```
</details>

<details>
  <summary>Workflow file</summary>

```
name: Replace Token Example

on:
  workflow_dispatch: # manually triggered

jobs:
  example:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4 # assuming that your repo contains src folder with example.txt file in it
    
      - uses: alexander-trishin/replace-token@v1
        with:
          target: ./src/example.txt
          variables: >
            - REPLACE_ME: REPLACED_VALUE
```
</details>

<details>
  <summary>File: after</summary>

src/example.txt

```
Lorem ipsum dolor sit amet, consectetur REPLACED_VALUE elit...
```
</details>

You can find more advanced usage examples in [this section](https://github.com/alexander-trishin/replace-token?tab=readme-ov-file#scenarios). If none of this works for you, you can try similar solutions available on [GitHub Marketplace](https://github.com/marketplace?query=replace+token).
